### ISSUE TITLE
TestResolveAddress should allow overriding test image

### ISSUE THREAD

**Issue by mgencur** [knative-extensions/kn-plugin-event#304]
The test is located [here](https://github.com/knative-extensions/kn-plugin-event/blob/main/test/pkg/k8s/addressresolver_test.go#L34) and it consumes test cases defined in pkg/k8s/test/addressresolver_cases.go.
The test case [hardcodes](https://github.com/knative-extensions/kn-plugin-event/blob/main/pkg/k8s/test/addressresolver_cases.go#L124) the gcr.io/knative-samples/helloworld-go image which is not multiarch.
We would like to be able to define TEST_IMAGES_HELLOWORLD_GO env variable to override the image. The image resolver should be able to replace the hardcoded one with the one define via env variable. This way we could pass a multiarch version of that image, for example.

Similar approach is used for other E2E tests, for example the wathola-forwarder image can be overridden via env variable TEST_IMAGES_WATHOLA_FORWARDER: [link](https://github.com/knative-extensions/kn-plugin-event/blob/main/test/e2e/kn_service.go#L99)

The TestResolveAddress test is the only E2E test which doesn't allow overriding the test image.

**Comment by cardil** [comment]
@mgencur The `gcr.io/knative-samples/helloworld-go` is provided from the Serving sources, right? We should open up an issue there to make it multi-arch.

**Comment by cardil** [comment]
> @mgencur The `gcr.io/knative-samples/helloworld-go` is provided from the Serving sources, right? We should open up an issue there to make it multi-arch.

Scratch that. Those images are provided from docs repo. Some time ago there where updated to use multi-arch: https://github.com/knative/docs/pull/5273

Unfortunately, only `arm64,amd64` is configured:

https://github.com/knative/docs/blob/c522018a2474384778c970b3487778207105fe3e/.github/workflows/knative-docs-image.yaml#L40-L46

**Comment by cardil** [comment]
See: https://github.com/knative/docs/issues/5718
